In [2]:
import numpy as np

NTESTS = 1000
paths = []
NVERTICES = 50
V = np.arange(NVERTICES)

from graph import *
def test():
    g = Graph(gen_random_graph(NVERTICES, 2))
    p = np.random.choice(V, size=2)
    return g.shortest_path(*p)

results = [test() for _ in range(NTESTS)]

In [3]:
print(results[:5])

[[32, 8, 41, 11], None, [27, 38], [34, 27, 31, 11, 44, 7, 21, 43, 36], [6, 3, 22, 46, 44, 18]]


In [6]:
def test(v, e):
    g = Graph(gen_random_graph(v, e))
    p = np.random.choice(v, size=2)
    return g.shortest_path(*p)

In [14]:
vCounts = [x ** 2 for x in range(3, 10)]
eCounts = list(range(1, 8))

m, n = len(vCounts), len(eCounts)

results = np.zeros((m, n))

for i in range(m):
    for j in range(n):
        for _ in range(NTESTS):
            p = test(vCounts[i], eCounts[j])
            if p is not None:
                results[i][j] += 1

In [15]:
print(results)

[[ 358.  774.  917.  972.  991.  997.  998.]
 [ 308.  783.  946.  979.  989.  996. 1000.]
 [ 230.  782.  934.  972.  987.  997.  999.]
 [ 219.  794.  949.  986.  990.  998. 1000.]
 [ 154.  801.  928.  982.  992.  995.  999.]
 [ 158.  785.  934.  972.  992.  998.  996.]
 [ 134.  801.  948.  972.  990.  999.  999.]]
